language: node_js
node_js:
   - "node"
   - "8"
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g eslint
script:
  - yarn lint
  - yarn test
cache:
  - yarn