
language: node_js

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
- export PATH=$HOME/.yarn/bin:$PATH


matrix:
  include:
  - node_js: '8.0'
    script:
      - yarn test

cache:
  yarn: true
  directories:
    - node_modules
    - .jest/cache